### ISSUE TITLE
Unable to find the plugin settings. Help please?

### ISSUE THREAD

**Issue by AeroMartin** [vnen/godot-tiled-importer#101]
**Plugin version**
Tiled version 2.2; Godot version 3.0.6
Downloaded from the AssetLib

**Issue description**
I have a hard time searching for the plugin's settings in Godot 3.0.6. I stumbled upon another post where another person had the same inquiry (Issue #58). The suggested solution?
> "Is the **Tiled file** selected in the FileSystem dock?"

 So, when I dug into the files of the plugin, I saw a file called "Tiled.cfg". But when I check into the FileSystem in Gobot, it's not there.

**Question 1:** Is the "Tiled file" referencing "Tiled.cfg"?
**Question 2:** Why can't I have access to it via Godot?

**Comment by vnen** [comment]
What I meant is the map file you made on the Tiled editor. Those settings are per imported file, so you need to select the file you want to import to change the settings (`your-map.tmx` or `your-map.json` depending on the format you saved). The maps are shown in Godot's FileSystem dock.

Sorry for the delay, I have been traveling for a while and am still catching up.

**Comment by AeroMartin** [comment]
Oh, okay. Thank you very much for your help.
