### ISSUE TITLE
tiles get imported as a checkerboard 

### ISSUE THREAD

**Issue by Aaron-Fleisher** [vnen/godot-tiled-importer#103]
**Plugin version**
2.2

**Issue description**
When importing tilemaps (.tmx), the tiles get imported like a checkerboard.

I thought it was related to https://github.com/godotengine/godot/issues/23631, and the PR that fixes it is https://github.com/godotengine/godot/pull/23625, however, I just got done compiling minutes ago [using this commit](https://github.com/godotengine/godot/commit/942855a9ee376ce6ee30a25674856ba64316b548). And the problem still continues to persist. I am not even sure if it's the same issue though.

**Steps to reproduce**
 - Create new map with tiled
 - Drag it into a scene
 - ![](https://i.gyazo.com/b44b45733378f05fadc193c8519ed1a6.gif)
 - Here is the map, just a new blank one
 - ![](https://i.gyazo.com/ebcfffec4f9389ccc4929a4c8ddef494.png)

**Sample map or tileset**
![grassland_64x64](https://user-images.githubusercontent.com/43447253/49011805-3da6d980-f12c-11e8-9661-96e0ba0272e6.png)

**Comment by Aaron-Fleisher** [comment]
Here are the contents of the .tmx file:
```
<?xml version="1.0" encoding="UTF-8"?>
<map version="1.2" tiledversion="1.2.1" orientation="orthogonal" renderorder="right-down" width="25" height="25" tilewidth="64" tileheight="64" infinite="0" nextlayerid="2" nextobjectid="1">
 <tileset firstgid="1" name="grassland_64x64" tilewidth="64" tileheight="64" tilecount="256" columns="16">
  <image source="../../Textures/Tilesets/grassland_64x64.png" width="1024" height="1024"/>
 </tileset>
 <layer id="1" name="Tile Layer 1" width="25" height="25">
  <data encoding="csv">
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18
</data>
 </layer>
</map>
```

Seems like this data doesn't much the checkerboard style. There would be 0's if it was a blank tile?

**Comment by dashorty** [comment]
@Aaron-Fleisher I have the same issue. Only every second tile is loaded into the tilemap.
Also the 1. tile not loaded.

**Comment by Aaron-Fleisher** [comment]
@dashorty Yeah, something must have happened in the past 2 weeks or so. I'm looking at the history logs of tile_map.cpp and some other nodes. Can't find anything

**Comment by dashorty** [comment]
@Aaron-Fleisher something with the 
`tile_data = PoolIntArray()`
from the tilemap must be wrong i think.

**Comment by Aaron-Fleisher** [comment]
Think it could be related to https://github.com/godotengine/godot/commit/672b1b19c033c093af01bfcb26ca509986942c19#diff-b70e65b070d931d45d2a99aa8943214b?

Because this was oddly working just fine around 2 weeks ago

**Comment by Aaron-Fleisher** [comment]
https://github.com/godotengine/godot/issues/23631#issuecomment-442227273

User says he found a temporary solution!

**Comment by vnen** [comment]
Sorry for the delay, I'll take a look soon.

I also want to point out that this plugin officially supports only stable Godot versions (because the master branch is a moving target, it's pretty much impossible to keep up).

**Comment by rosshadden** [comment]
@Aaron-Fleisher That workaround worked for me too. Thank you for mentioning it here!
