### ISSUE TITLE
Is using .TSX files only actually supported?

### ISSUE THREAD

**Issue by Sslaxx** [vnen/godot-tiled-importer#104]
**Plugin version**

Master (2.2), commit 89f4431f2bb7013547d78b8e43a2d8f67766af45. Cloned directly via GitHub.

**Issue description**
Using the latest version of Tiled, I created a .TSX file with an external image for the tiles. But the documentation suggests that only Tile*map*s - .TMX - are imported. Is this correct? I would like to only import tilesets and create maps/levels within Godot. The external image is imported as expected. The plugin has been enabled.

**Steps to reproduce**
Create a .TSX file, place it in a directory used by your project.

**Sample map or tileset**

[TSX_Example.zip](https://github.com/vnen/godot-tiled-importer/files/2620409/TSX_Example.zip)

**Comment by vnen** [comment]
It already supports importing only the tileset, either in TSX or JSON formats.

**Comment by Sslaxx** [comment]
.TSX files do not show up as an option.

**Comment by vnen** [comment]
I just realized there's a bug, the TSX importer has the wrong extension: https://github.com/vnen/godot-tiled-importer/blob/89f4431f2bb7013547d78b8e43a2d8f67766af45/addons/vnen.tiled_importer/tiled_tileset_import_plugin.gd#L36-L40

Changing this should enough to make it work.

**Comment by Sslaxx** [comment]
Bump. I note this has not been corrected in master.

**Comment by CrazyGuy108** [comment]
Shouldn't TMX files also be an option?

**Comment by Sslaxx** [comment]
If `TMX` files can also hold tilesets?

**Comment by vnen** [comment]
TMX can have the tilesets embedded, but do one really need to import a tileset from a TMX without importing the map?
