### ISSUE TITLE
Tileset is offset due to change in Godot 3.2 alpha

### ISSUE THREAD

**Issue by giulianob** [vnen/godot-tiled-importer#114]
**Plugin version**
Latest, Godot 3.2 alpha

**Issue description**
I was testing Godot 3.2 alpha and it looks like the tileset is shifted up due to a change in Godot 3.2. See https://github.com/godotengine/godot/pull/30204

**Steps to reproduce**
Import any tilemap from Tiled and you will see that it's shifted up. It's very obvious when drawing tiles since you will see that the tile above the one you click is actually drawn.

To fix it we should either modify the importer to properly set the flags that 3.2 expects OR specify the "compatibility" mode flag which then makes everything work as it did in 3.1

**Comment by vnen** [comment]
Just note that this plugin add offsets sometimes to make sure it looks like it was in Tiled. So you're not supposed to draw on an imported tilemap.

For what I understand the change did affect how it looks, so I consider this a bug (at least will be when Godot 3.2-stable is released)

**Comment by AndyGFX** [comment]
Hi, 
when do you have plan fix offset problem between objects and tilemap? 
Looks like diff is 16 pixels in y axis.

**Comment by svendixon** [comment]
> Hi,
> when do you have plan fix offset problem between objects and tilemap?
> Looks like diff is 16 pixels in y axis.

The offset moved from the upper left hand position of the tile to the lower left hand position of the tile. This caused maps to shift up by the height of your tiles. Tiles can be of any size.

**Comment by AndyGFX** [comment]
tilemap.compatibility_mode = true works good for me.

Thx.

**Comment by ja-brouil** [comment]
tilemap.position.y += cell_size.y

This fixes the issue. Or you can simply shift your map sprite by 16 pixels upward.

**Comment by tom-dreamviewer** [comment]
Don't know if it is a good solution, but changing

line 705
    result.tile_set_texture_offset(gid, Vector2(0, -tilesize.y))
to
    result.tile_set_texture_offset(gid, Vector2(0, 0))

solves issue, at least no offset being added to individual tiles. Don't know if it can break something afterwards, but I need such fix to exchange non animated tiles to animated ones in Godot.

**Comment by renickdp** [comment]
is there a official fix for this or using compatibility mode ok and won't break anything else? what does compat mode do?

**Comment by Aurora-Eluvia** [comment]
> 

Unfortunately, this one does break things if you have tiles of unusual size. You'd have to discard them if so.
