### ISSUE TITLE
Collisions not working

### ISSUE THREAD

**Issue by 5H4D0WILA** [vnen/godot-tiled-importer#116]
**Plugin version**
2.x
Downloaded from github

**Issue description**
The importing works, but it doesnt import the collisions

**Steps to reproduce**
Make a map with collisions in Tiled
Import it to Godot

**Sample map or tileset**
It is reproducable with any map

**Comment by alexkehayias** [comment]
I've also noticed this issue on Godot 3.1.2 stable. I've tried setting the object type to `area` and leaving it blank (as the wiki suggests) and not seeing any collision info in the sub-resources of the tileset.

**Comment by alexkehayias** [comment]
Update: the import did work with object type `area`. I noticed the automatic import doesn't always work after changing the tileset so I forced it by making some minor change to the map itself and it imported as expected. 

Collisions still don't seem to be considered with `Navigation2D.get_simple_path`, but I think that's a different problem.

**Comment by 5H4D0WILA** [comment]
okay, so i need to change the collision type to area?
and that should fix the collisions?

**Comment by 5H4D0WILA** [comment]
okay, it fixed it, thanks :)
