### ISSUE TITLE
Custom Properties

### ISSUE THREAD

**Issue by Chillance** [vnen/godot-tiled-importer#12]
Hey!

Great plugin! I looked quickly through the code and found no "properties", so it seems to me that there is no "custom properties" support here yet. I saw that this one had it: https://github.com/Geequlim/godot-code/tree/master/addons/tiled_importer but that plugin didn't work for me for some reason. So, could you add support to also include the "custom properties" one can specify in Tiled?

Thanks!

**Comment by vnen** [comment]
That plugin seems to create a script with the properties as exported variables. I don't like this idea because you may want to add a proper script the instanced scene.

I've been thinking in adding the properties as metadata to the scene and layers. Godot will eventually support viewing them within the editor so it'll be a cleaner approach IMO.

**Comment by Chillance** [comment]
Sounds good to me. I didn't post the above link to say to do like that, rather that they just have support for the custom properties. I actually didn't really look into the details regarding it.

So, when will "custom properties" be supported in this plugin do you think?

**Comment by vnen** [comment]
I'll try to work on it sometime this week.

**Comment by Chillance** [comment]
Ok, great.

**Comment by Chillance** [comment]
Cool! Thanks!

**Comment by Chillance** [comment]
So, I tried this, where do they show up in Godot?

**Comment by vnen** [comment]
@Chillance I just sent an update to the AssetLib, it should be approved sometime tomorrow. You'll have to update manually though, since there's no auto-update.

**Comment by Chillance** [comment]
Yes, I got your updated code running, but I'm not sure where I would see the custom properties show up in Godot. I didn't see the one I had added in Tiled.

**Comment by vnen** [comment]
Ah, sorry I misunderstood the question. There's no feature yet to show in editor GUI, but you can get through code using [`get_meta()`](http://docs.godotengine.org/en/stable/classes/class_object.html#class-object-get-meta) function.
