### ISSUE TITLE
Code in the wiki not working in Godot 3.2

### ISSUE THREAD

**Issue by jacopofar** [vnen/godot-tiled-importer#124]
The [post-import code in the wiki](https://github.com/vnen/godot-tiled-importer/wiki#post-import-script-modify-the-imported-scene) doesn't work in Godot 3.2, the two `if` use the `extends` operator instead of `is`.

Godot 3.2 doesn't accept this syntax, but replacing it with `is` it works fine.
Also the code refers to `set_pos` and `get_pos` methods which do not exist, one need to use the `position` attribute now.

**Comment by Calinou** [comment]
`extends` was replaced with `is` for the purposes of type checking in Godot 3.0, so the example code no longer works since a long time ago.

**Comment by vnen** [comment]
> It would be a good idea to make the wiki publicly editable, so anyone can update the documentation without requiring you to be around.

Done.

**Comment by Calinou** [comment]
Thanks! I updated the import script. This issue can now be closed.

**Comment by vnen** [comment]
Thank you!
