### ISSUE TITLE
Add support for tiles normal maps

### ISSUE THREAD

**Issue by Lertsenem** [vnen/godot-tiled-importer#143]
Occluders are already taken care of, but normal-maps for each tile can also really enhance 2D lighting. Unfortunately, those are really tedious to set by hand in Godot.

Could it be possible to add a feature allowing for normal maps auto import using this plugin?

Maybe using a custom property in Tiled containing the path to the normal map image? Maybe with a default value being the tile image path with a ".normalmap" suffix?

**Comment by jakes1403** [comment]
Already solved with the custom materials feature added in #141

**Comment by vnen** [comment]
Closing as solved (the merged PR is #145).
