### ISSUE TITLE
Document importing features

### ISSUE THREAD

**Issue by vnen** [vnen/godot-tiled-importer#15]
Some people seems to have trouble importing collision shapes. Better usage information and maybe some tutorial is needed.

----

A little list of things there are not well documented:

- [x] The imported scene should not be edited directly (use inheritance or instancing)
- [x] How to create collision/navigation/occluder shapes (cf. https://github.com/vnen/godot-tiled-importer/issues/18#issuecomment-275508192)
- [x] How to set up custom properties and read the metadata in Godot
- [x] The possible `type` values for shapes and objects in an object layer
- [x] Post-import script usage (cf. #29)

**Comment by NathanLovato** [comment]
Thanks for the extra to-do. I'm on it.

Regarding the post-import script, do you have any use examples? I guess you could use the imported metadata to append scenes to the level automatically. Interactive elements likes plants, doors, whatever -
 anything you should design in Godot. Any other ideas?

**Comment by NathanLovato** [comment]
Is this the type of content you're looking for? The only missing bits are the metadata part and fleshing out the post-import section to show how to use metadata there. But gotta test it first.

[godot-tiled-importer-docs-notes.pdf](https://github.com/vnen/godot-tiled-importer/files/1197225/godot-tiled-importer-docs-notes.pdf)

**Comment by vnen** [comment]
Thanks Nathan! Yes, this is the content I'm thinking about.

About metadata, there isn't any at the tile level (because Godot can't handle it natively). It does add to objects since those are imported as nodes. I guess it could be used to add instanced scenes for interactive elements. Could also be used to change some property of the node.

**Comment by NathanLovato** [comment]
It's close to done, but I'm stuck with the metadata: in the version from the asset library, on Godot 2.1.3, it's nowhere to be found. I checked the inspector on the bodies and shapes (including the resources) where I'd expect to find them, but couldn't. Also, after saving the file to .tscn, a search shows the key, value pairs aren't there either.

Could you give me a hand on this one? Also, should I make the text part of the readme file? And where should the pictures be stored, maybe a 3rd party website like imgur so it's not part of the repo? I'll do a PR as soon as it's finished.

**Comment by vnen** [comment]
The metadata can't be seen anywhere in the editor. They should be somewhere in the scene file, but I don't if `.tscn` support them. You can only access that via code.

About the location, we could either make a `doc` folder here with a few files (including images) or use the GitHub wiki. Then the Readme can link to it.

**Comment by NathanLovato** [comment]
I've got 3 objects on 2 object layers with custom string properties, but `get_meta_list()` always returns an empty array. The TMX file is from Tiled 1.0. Do you have any sample project with working metadata I could use for testing purposes?

**Comment by NathanLovato** [comment]
Here's the text with all requested aspects covered. Could you tell me if it's okay? All that's left then would be testing the post-import script code with metadata.
[godot-tiled-importer-docs-notes.pdf](https://github.com/vnen/godot-tiled-importer/files/1199769/godot-tiled-importer-docs-notes.pdf)

**Comment by vnen** [comment]
Are you using the AssetLib version? I pushed a few fixes here recently.

**Comment by NathanLovato** [comment]
Ah right, it works with the addon from the repo - it was the one from the asset store. Okay, the tutorial is pretty much ready to push now. Could you give me access to the wiki? Or I can send you the files when I'm back from the office and let you push everything. I think I need to be added to the repo as a collaborator to use the wiki.

**Comment by vnen** [comment]
I added you as collaborator. Thanks again for working on this and sorry that I'm quite busy in the past few days to answer you promptly.

**Comment by NathanLovato** [comment]
No worries. The doc is up for review: [wiki page](https://github.com/vnen/godot-tiled-importer/wiki)

**Comment by vnen** [comment]
I think it's okay to have all in a single page. I'll try to review it later today.

**Comment by vnen** [comment]
I guess we can close this now, the features are documented in the [wiki](https://github.com/vnen/godot-tiled-importer/wiki). Thanks again, @NathanLovato!

**Comment by NathanLovato** [comment]
You're welcome!
