### ISSUE TITLE
Tiled Editor has updated and Type is now called Class

### ISSUE THREAD

**Issue by LunaBold** [vnen/godot-tiled-importer#157]
I have tried editing the code to replace Type with Class but it comes back with errors about "name" being a invalid property. unfortunately the debug isn't helpful in fixing the issue myself. Collisions still work as intended but i am unable to create occlusion polygons.

**Comment by cromerc** [comment]
On the website this is mentioned:

> Type -> Class
> 
> In Tiled 1.9, the "type" attribute previously supported only on objects and tiles has been renamed to "class" and can now be applied to all data types.
> 
> For compatibility with previous Tiled versions and other software, there is a new "Compatibility Version" option, which can be set to "Tiled 1.8" to make the class still write out as "type" for objects and tiles.

So there is an option to put it into compatibility mode with 1.8 so that it uses type instead of class.

That option will get it working for you with this plugin.

**Comment by LunaBold** [comment]
oh! thank you! i had no idea that was a option, i'll check it out!

**Comment by cromerc** [comment]
I opened a PR to add 1.9 compatibility, if you have trouble getting the 1.8 compat working you can try with my patch.

**Comment by erniel** [comment]
where do i find that option to put it into compatibility mode with 1.8?

**Comment by cromerc** [comment]
The option is in project settings, it only shows up while you have a project open.
