### ISSUE TITLE
Need help, keep getting same error when importing tilemap

### ISSUE THREAD

**Issue by Seanfy** [vnen/godot-tiled-importer#17]
Hi,

This is a great plugin and I really like it. 

But after I updated the plugin today, I'm getting the following error when importing tilemap, even it's a simple tilemap with just one layer. Couldn't find any clue on what happened, can you help me? Many thanks!

SCRIPT ERROR: build: Invalid get index '1' (on base: 'Dictionary').
          At: res://addons/vnen.tiled_importer/tiled_map.gd:197

**Comment by vnen** [comment]
Can you attach a sample Tiled file that gives this error?

**Comment by Seanfy** [comment]
sorry I couldn't find the old tiled file because I overwritten it with a new one. Seems like it's because I updated Tiled and re-save the old file in the new Tiled, when I created a new Tiled file everything works fine now...

**Comment by vknecht** [comment]
Hello,
here's a TMX file bugging on invalid index '0', made with Tiled 0.17.2 (Fedora 25)...
[isotest.zip](https://github.com/vnen/godot-tiled-importer/files/851274/isotest.zip)
