### ISSUE TITLE
Importing map causes some tiles to be blank or other tiles

### ISSUE THREAD

**Issue by Limb** [vnen/godot-tiled-importer#20]
When I Import a simple map, some of the tiles are replaced with other tiles or left blank. 

Looking at the tileset in the godot editor it seems all the tiles are created properly, but the actual tileset ends up with random tiles on the map or a empty tile.

![tiled view](https://cloud.githubusercontent.com/assets/240752/23341242/8fe5d3d4-fc11-11e6-879a-a89ac4884264.PNG)

![in-godot](https://cloud.githubusercontent.com/assets/240752/23341241/8695f854-fc11-11e6-9cae-3e2dddf8d793.PNG)

**Comment by Limb** [comment]
Looking closer it appears the tileset numbers don't match up after the first row. Thus the gids are not aligning to the tiles they should anymore.

**Comment by vnen** [comment]
Can you send a sample Tiled file that have this behavior?

**Comment by Limb** [comment]
So the problem was that my tileset had an extra column that was not a full tile size. This was throwing off the importer. This was an issue on my behalf not the plugin, all is good!
