### ISSUE TITLE
Loading image from non-relative directory fails

### ISSUE THREAD

**Issue by Limb** [vnen/godot-tiled-importer#21]
When using assets that are not stored in the same relative folder as the tilemap, the loader appends the entire filepath to the local path, causing an error.

Example:
TMX says image source is "D:/assets/tile.png"
TMX is stored as "C:/game/levels/level1.tmx"

The importer tries to load "C:/game/levels/D:/assets/tile.png"

**Comment by vnen** [comment]
Yeah, I think it never checks if the path is absolute or not.
