### ISSUE TITLE
"Invalid GID" error when an object doesn't have GID set.

### ISSUE THREAD

**Issue by HummusSamurai** [vnen/godot-tiled-importer#22]
I was testing the addon on one of Tiled's example files (/examples/orthogonal-outside.tmx) -- the provided objects do not have a GID and their id's are arbitrary (do not point to an actual tileset) and so an import error was thrown.

I traced it to[ this snippet.](https://github.com/vnen/godot-tiled-importer/search?utf8=%E2%9C%93&q=invalid+GID&type=)

Wouldn't it be possible to silently ignore this warning and use any random tile for the objects? (Assuming it's necessary to have one as a placeholder).

This seems to make more sense, as setting object GIDs is, [by design](http://doc.mapeditor.org/reference/tmx-map-format/#object), optional, and this is one area where we're breaking compatibility with Tiled when it could perhaps be avoided.

What do you think?

P.S. Thanks for this addon, I must say it's really great! :D

**Comment by HummusSamurai** [comment]
I want to also add that I tried adding a gid property to the tiled objects (and their layer) and it still didn't work, and at this point I realised I don't know what's happening.

Any tips about how I should be implementing object gid's?

**Comment by vnen** [comment]
I can't reproduce this error, the `orthogonal-outside.tmx` import fine.

This plugin does not expect objects to have a GID. The linked snippet has an `else` statement to treat objects without a GID, which import the shapes as StaticBodies.

**Comment by HummusSamurai** [comment]
@vnen If you can't reproduce it then I'll make sure to test again and provide a sample project if it persists.

**Comment by HummusSamurai** [comment]
I tried the problem with an empty project and it did not occur, so I am assuming it had something to do with my project back then.

Closing this issue as it's not relevant anymore.
