### ISSUE TITLE
Re-import / lag each time Godot window is re-focused (Windows)

### ISSUE THREAD

**Issue by DjPale** [vnen/godot-tiled-importer#25]
I've been testing this plugin and it works great. I noticed that Godot does a brief pause and re-imports almost each time I focus the editor window - even though I didn't change the source files. The auto-reload is great in itself, but when it happens often the lag is just enough to annoy 😉 

I was wondering if this is a Godot-engine-related thing

Currently using v2.1.2-stable (through Steam) on Windows 10

**Comment by DjPale** [comment]
Discussed this in the IRC channel - probably a Godot-issue, will open issue there

**Comment by vnen** [comment]
This is a Godot issue. It might have been solved in 2.1.3 so please test there.
