### ISSUE TITLE
Custom property doesn't appear as metadata

### ISSUE THREAD

**Issue by Wildos** [vnen/godot-tiled-importer#28]
Hello,

I'm trying to import a map with an object which contain a custom property: 

![image](https://user-images.githubusercontent.com/8025788/27083980-9d87933c-504a-11e7-8098-6b18f23815a9.png)

I check the checkbox is check in the import window

![image](https://user-images.githubusercontent.com/8025788/27084065-d4142438-504a-11e7-9697-530df368526c.png)

But my test script I put on the objects layer don't see anything: 
```func _ready():
	print("Metadata list:")
	for i in get_children():
		print(i.get_meta_list())
```
Here the output i have :
```
	Metadata list:
	[]
```

I use the 2.1.3 version of Godot (the Steam one) and the last version of Tiled version 1.0.0

What am I doing wrong ?

**Comment by vnen** [comment]
Oh, I don't think it sets metadata for objects, only for map and layers.

**Comment by Wildos** [comment]
The problem is a lack in tiled-importer or in Godot capability ?

**Comment by vnen** [comment]
It is missing in this plugin.

**Comment by Wildos** [comment]
I will read the code and try to implement it so

**Comment by Wildos** [comment]
The import of custom property for object work with .json files but not with .tmx.
The problem must come from the convert function
