### ISSUE TITLE
Post_import function: scene is not affected by my modification

### ISSUE THREAD

**Issue by Wildos** [vnen/godot-tiled-importer#29]
Hello,

I'm trying to automatically add a player to the scene.

here the code of my post_import script:

```
extends Node

var player = preload("res://Scene/Player.tscn")

func _ready():
	pass

func post_import(scene):
	var p = player.instance()
	scene.add_child(p)
	return scene
```

The scene don't seem to be affected by my change since the player isn't in the scene.
But if I return "p", the player instance, the scene imported is an copy of the player scene which mean the code is correctly executed.

I'm still new to Godot Engine, this code should work, right ?

**Comment by vnen** [comment]
Try to do `p.set_owner(scene)` just before returning.

**Comment by Wildos** [comment]
it works, thank you
