### ISSUE TITLE
Can't import with post-import script.

### ISSUE THREAD

**Issue by chelovekbeznika** [vnen/godot-tiled-importer#32]
Post-import contains only "return string"
In output of editor next error appears:
 res://addons/vnen.tiled_importer/tiled_importer_plugin.gd:101 - Invalid call. Nonexistent function 'new' in base 'GDScript'.
Using Godot stable 2.1.3. Stopped to work unexpectedly (before certain moment with post-import script was possible)

**Comment by vnen** [comment]
If it literally contains only `return string` it is not a valid GDScript.  Can you post the complete script here?

Also, take a look at the Readme file which describes how post-import scripts should be made:

> The selected script will have its `post_import(scene)` method run. This
enables you to change the generated scene automatically upon each reimport.
>
> The `post_import` method will receive the built scene and **must** return the
changed scene.

**Comment by chelovekbeznika** [comment]
Thanks for quick response!
I toggled in project settings "active/inactive" for import plugin and bug went off.
If this will return, I'll send my observations to you ASAP. Just in case, I'am suggest to keep this issue open couple days.

PS Script now literally looks like this:

# class member variables go here, for example:
# var a = 2
# var b = "textvar"

func post_import(scene):
	return scene

**Comment by chelovekbeznika** [comment]
Bug returned =( And it certainly not about plugin settings.
```GDScript
# class member variables go here, for example:
# var a = 2
# var b = "textvar"

func post_import(scene):
	var blocks = 0
	self.search_blocks(scene, level)
	var file = File.new()
	file.open("res://test/post_import.txt", File.WRITE)
	file.store_float(blocks)
	file.close()
	return scene
	
func search_blocks(node, level):
	if node.get_meta("block"):
		blocks += 1
	for child in node.get_children():
		search_blocks(node, level + 1)
```

**Comment by vnen** [comment]
Does your script have `extends Reference` on the first line? Doesn't need to be a `Reference`, can be another type, but the line is mandatory. If it is crashing the problem is mostly on Godot than in this plugin.

**Comment by chelovekbeznika** [comment]
Added. No effect.

**Comment by chelovekbeznika** [comment]
It looks like problems with my code =( I corrected some mistakes and instead of tiny checkbox got fully crush of Godot editor. Code here (I suspect it something wrong with recursion here)

```GDScript
extends Reference
# class member variables go here, for example:
# var a = 2
# var b = "textvar"
var blocks = 0

func post_import(scene):
	self.search_blocks(scene, 0)
	var file = File.new()
	file.open("res://test/post_import.txt", File.WRITE)
	file.store_float(self.blocks)
	file.close()
	return scene
	
func search_blocks(node, level):
	if node.get_meta("block"):
		self.blocks += 1
	for child in node.get_children():
		search_blocks(node, level + 1)
```

So, real issues here - plugin can't say what exactly wrong with post-import script. Which less fatal.

**Comment by chelovekbeznika** [comment]
found error. In method search_blocks recursion should be called in this manner:
```GDScript
search_blocks(child, level + 1)
```
instead of
```GDScript
search_blocks(node, level + 1)
```

So issue could be closed. Only problem in plugin here: misleading error messages. Thanks for your help.
PS Now I know what godot allows 100 levels of recursion and fails at 500 levels.
