### ISSUE TITLE
Can't import Tilemaps that have TileSets with different sizes.

### ISSUE THREAD

**Issue by radicaled** [vnen/godot-tiled-importer#33]
I have a Tiled map whose tile width / height is 32x32.

However, I have a tileset that's a collection of images, with some images larger than 32x32 -- 64x64 or higher[0]. The add-on won't import them because of this check: https://github.com/vnen/godot-tiled-importer/blob/b1f754d3b9474b826d6a56fc098a2ab3966d608c/addons/vnen.tiled_importer/tiled_map.gd#L745

I've been exporting to .tmx format, if that helps.

[0] The kind of Tileset that gets generated when you do this: File -> New -> New Tileset, select "Type: Collection of Images". This kind of Tileset lets you mix and match without having to rely on a single huge tilesheet.

**Comment by vnen** [comment]
Will have to check the differences between Godot and Tiled for this one. I know Godot doesn't care about the tile size in the TileSet, but in the TileMap node it has a single tile size.

**Comment by vnen** [comment]
BTW, if you have any sample map that reproduce this I would be glad.

**Comment by radicaled** [comment]
https://gist.github.com/radicaled/139a9375d3c45a19a63addeda54938a6

You'll have to make a random 64x64 file called "enemy_command.png" in the same folder.
