### ISSUE TITLE
Importing tiled output file containing multiple layers isn't Y-aligned correctly in Godot

### ISSUE THREAD

**Issue by mrnod** [vnen/godot-tiled-importer#36]
Hard to describe but 2 screenshots attached.

i) Create tiled file containing multiple layers

ii) Import into Godot via Tiled Map Importer v1.5

The layers have strange vertical offsets which isn't how they appear in Tiled.

Apologies if this is a newbie mistake.
![godot_imported_tiled_layers](https://user-images.githubusercontent.com/2803308/28314639-48e6622a-6bb3-11e7-8264-b43aede74823.png)
![tiled_layers](https://user-images.githubusercontent.com/2803308/28314640-48e811ec-6bb3-11e7-952f-c01c48e1e11c.png)

**Comment by vnen** [comment]
I think the plugin doesn't take the layer offset into account.

**Comment by AndyGFX** [comment]
Fix for tile used as object:
line 542
					var pos = Vector2()
					if obj.has("x"):
						pos.x = float(obj.x) **+ cell_size.x/2**
					if obj.has("y"):
						pos.y = float(obj.y) **- cell_size.y/2**

**Comment by vnen** [comment]
Sorry for the delay. I think this is fixed in master.

**Comment by vnen** [comment]
I assume this is already fixed (just updated the plugin in the AssetLib).
