### ISSUE TITLE
Support for Infinite maps

### ISSUE THREAD

**Issue by HeadClot** [vnen/godot-tiled-importer#51]
In the upcoming Tiled 1.1.0 release there is a feature Called [Infinite maps](http://docs.mapeditor.org/en/latest/manual/using-infinite-maps/).

Would it be possible to support this new feature?

Just curious,
HeadClot

**Comment by vnen** [comment]
I don't see what's needed to support. This seems like an editor-specific feature, the final exported map would have a finite size anyway.

**Comment by Limb** [comment]
It looks like infinite maps are not supported. Upon opening a infinite map the layers and tile sets are imported correctly but the tile map is blank.

**Comment by vnen** [comment]
Yeah, later I saw that infinite maps are split in chunks, so supporting this will require some changes.
