### ISSUE TITLE
Not compatible with Godot 3.0b

### ISSUE THREAD

**Issue by bferguson3** [vnen/godot-tiled-importer#53]
Hi,

I'm able to edit but no longer import new Tiled maps using Godot 3, as the import functionality has radically changed. 

Is there a way to import now without importing into Godot 2 and exporting the scene?

Thanks.

**Comment by vnen** [comment]
I will eventually update to work with Godot 3 before the final release. For now you can try the PR #50 and see it works.

**Comment by vnen** [comment]
BTW, the [`godot-3` branch ](https://github.com/vnen/godot-tiled-importer/tree/godot-3) here is pretty much complete. Will soon publish to the asset library.

**Comment by HummusSamurai** [comment]
I suggest you also make the godot-3 branch the default github branch, since if I wasn't watching the comments I wouldn't have noticed it :b

**Comment by vnen** [comment]
I'll merge to master soon, and it wasn't really working before, so it wouldn't make much difference.

**Comment by vnen** [comment]
`master` was updated. Still not 100% but most of functionality is there. Old version is on the [`1.x` branch](https://github.com/vnen/godot-tiled-importer/tree/1.x). The 1.x will still be updated while Godot 2.1.x is supported.
