### ISSUE TITLE
polygon shape is hollow

### ISSUE THREAD

**Issue by indiemaniac** [vnen/godot-tiled-importer#55]
i created a polygon shape in tiled for collision.
when i import to godot only the lines appear(show collision debugger option) and the player will fall thru them

![godottiledbug](https://user-images.githubusercontent.com/28846159/33748264-5f46a9b8-dbbf-11e7-8dd2-b88c980aff95.gif)

**Comment by vnen** [comment]
Can you attach a sample Tiled map with this issue?

**Comment by indiemaniac** [comment]
1 sec
