### ISSUE TITLE
noob need help with custom properties

### ISSUE THREAD

**Issue by indiemaniac** [vnen/godot-tiled-importer#56]
how do i access custom properties?
first time i added properties to the tile itself, which i think is not suposed to work right now
next i removed those and added properties to a collision shape which i think should work?
what object do i access to get the metadata

**Comment by vnen** [comment]
Custom properties are only applied to layers and objects in an object layer.

**Comment by indiemaniac** [comment]
so it works in objects in an object layer and layer themselves.
i got it working thanks a lot 👍
