### ISSUE TITLE
tile_meta doesn't exist?

### ISSUE THREAD

**Issue by Lucrecious** [vnen/godot-tiled-importer#57]
Hi, I can't seem to use tile_meta to access Tiled .tsx Tile properties - even when I've enabled the import option.

I searched tile_meta, and set_meta in the repository and "tile_meta" doesn't seem to exist.

How do I access custom Tile properties now?

**Comment by vnen** [comment]
Yeah, it's not implemented yet for the master branch. I'll try to take some time next week to wrap up my todo list and publish to the asset lib.

**Comment by vnen** [comment]
Fixed by 89af470.
