### ISSUE TITLE
Seeing edge artifacts in pixel art tiles; How to access/change import settings for tiled import plugin?

### ISSUE THREAD

**Issue by olsonjeffery** [vnen/godot-tiled-importer#58]
I'm using Godot 3.0 RC1 mono build on OSX Sierra, with godot-tiled-importer cloned from this repo in the project's addons folder

The README mentions the presets (default/pixel art). I've noticed some edge artifacts in the tilesets I'm importing (gaps between solid color tiles and lines around the tiles in general that I assume are because of filter/mipmap stuff) and i want to switch to the "pixel art" preset in order to see if that addresses the issue (I've already disabled filtering and mipmaps in the project settings).

But I can't find where this is done.. the "import" tab in the editor doesn't show anything (and the "presets" button is empty). Here is what I see in the Import tab:
![screen shot 2018-01-21 at 10 23 54 am](https://user-images.githubusercontent.com/10408/35196259-4885a186-fe95-11e7-9f50-d757e41d7083.png)

I can't find any settings in project settings or editor settings related to the plugin. The README doesn't say exactly where these settings are, and I'm still getting used to Godot 3.0, so if you could be more explicit about where the settings are and how you can modify them, I would be grateful.

Thanks.

**Comment by olsonjeffery** [comment]
Here's the artifacts I see, btw:
![screen shot 2018-01-21 at 10 56 05 am](https://user-images.githubusercontent.com/10408/35196586-ce7b3a7c-fe99-11e7-87f0-88abead8c34d.png)

Here's what it looks like in tiled:
![screen shot 2018-01-21 at 10 56 42 am](https://user-images.githubusercontent.com/10408/35196588-d62a59e2-fe99-11e7-98e6-f62d7d041f6b.png)

Here are my relevant project settings:
![screen shot 2018-01-21 at 10 57 37 am](https://user-images.githubusercontent.com/10408/35196591-ed491424-fe99-11e7-8142-6a0a601a37ba.png)

**Comment by vnen** [comment]
> But I can't find where this is done.. the "import" tab in the editor doesn't show anything (and the "presets" button is empty). Here is what I see in the Import tab:

Is the Tiled file selected in the FileSystem dock? The options will only show if the file is selected.

> Here are my relevant project settings:

This is the anisotropic filter, it's only relevant for 3D. The actual image filter is on the import options of the images themselves, so you need to select an image in the FileSystem dock, change the flags (or select the 2D Pixel preset), reimport, and save this preset as default (in the Preset menu). This won't change the already imported images, so you can delete all the `.import` files from your project to force the editor to reimport with the new default.

**Comment by olsonjeffery** [comment]
>Is the Tiled file selected in the FileSystem dock? The options will only show if the file is selected.

This is what I was missing. Thank you for educating me on this. All of my previous experience is with using the 2.x branch and I didn't really interact w/ the Filesystem panel at all.

This addresses my question; I will close the issue.

Thanks again.
