### ISSUE TITLE
ability to specify object shapes that come over as arbitrary Area2Ds

### ISSUE THREAD

**Issue by olsonjeffery** [vnen/godot-tiled-importer#59]
Right now the importer supports collision geometry, occluders, etc based on annotation in the object properties...

Would it be possible to extend this to allow bringing over something as an Area2D (instead of e.g. a StaticBody2D)? This, combined with the custom property annotations which convert to metadata, would allow some powerful automated functionality w/i games (e.g. creating teleporters to connect tiled maps).

I imagine this would be pretty straightforward to implement and I'm open to putting together a PR, I just haven't bothered to look at the plugin code, yet. Any pointers would be appreciated.

As it is, I think I could implement this in my own project via scraping and recreating an area2D at the position of a staticbody2d and removing the child beneath it and adding that collision shape to the newly created Area2D instead. But it would seem cleaner and less work at run time to handle this during the import (also wouldn't have to move over metadata).

**Comment by vnen** [comment]
Yeah, I thought about this. Could be set as the Type property in Tiled (maybe with `area` type) and checked by the importer. Should be an easy to do and likely just replacing this line with the check:

https://github.com/vnen/godot-tiled-importer/blob/36669f413ca2d82c14a56a92c9eb3a6292e02715/addons/vnen.tiled_importer/tiled_map_reader.gd#L275
