### ISSUE TITLE
Can import .tmx file into godot:

### ISSUE THREAD

**Issue by marcusViniciusMP** [vnen/godot-tiled-importer#62]
returns, this error msg:
 res://addons/vnen.tiled_importer/tiled_map.gd:169 - Invalid operands 'int' and 'String' in operator '+'

**Comment by vnen** [comment]
Never thought `name` would not be a string. I guess this can be fixed with a cast.

**Comment by vnen** [comment]
Fixed by 50ea662d249156618d24c77ee3e11bca3fe76e50.

**Comment by marcusViniciusMP** [comment]
now the error says ICCP: known incorrect sRGB profile, on
drivers/png/image_loader_png.cpp:66

**Comment by vnen** [comment]
That's not really a problem, just a warning from libpng. There's a guide here showing how to fix the images to not show that warning: http://docs.godotengine.org/en/stable/learning/workflow/assets/managing_image_files.html?#fixing-pngs-iccp-chunk
