### ISSUE TITLE
i create a level on tiled then when i import it...

### ISSUE THREAD

**Issue by marcusViniciusMP** [vnen/godot-tiled-importer#63]
its goes messed in godot, all the wrong tiles in wrong positions...

i try to implement the fix of #36 but didnt work for me...
![tilemaperror1](https://user-images.githubusercontent.com/32377313/35464533-8b6c5a34-02dd-11e8-919f-ce59815d0110.png)
![tilemaperror2](https://user-images.githubusercontent.com/32377313/35464541-90db001a-02dd-11e8-9c48-9f9e1766c2ec.png)

**Comment by vnen** [comment]
Do you have a sample map you can provide that reproduces this issue?

**Comment by marcusViniciusMP** [comment]
yes i do. 
![smb3world1_](https://user-images.githubusercontent.com/32377313/35465105-e7ed376c-02e0-11e8-84f9-9331f596cd5d.png)
other thing happened, besides in tiled all the tiles stay correctly aligned and with no spaces between them, when i import ir to godot it cames with gaps between ....

**Comment by marcusViniciusMP** [comment]
i think this could be better to see whats happening...
![tiles_correct](https://user-images.githubusercontent.com/32377313/35465581-300ed250-02e4-11e8-8fd9-4d9286467d06.png)
![tiles_wrong](https://user-images.githubusercontent.com/32377313/35465582-303609b0-02e4-11e8-9c3a-9e81751b35bf.png)

**Comment by vnen** [comment]
Thanks, I'll check that soon.

**Comment by marcusViniciusMP** [comment]
hi, i found a simple hack for the gaps between the tiles, i just save first the tileset in tiled editor as .png with no gaps between them, so i load it again in tiled to use as source for the actual tileset to export for godot. since i import all the blocks there i do the rest in godot also.
