### ISSUE TITLE
tile_meta Dictionary Not Populated with Custom Properties

### ISSUE THREAD

**Issue by atomicbeef** [vnen/godot-tiled-importer#65]
Using Godot 3.0-stable and version 2.0.0 of this plugin, I can't get custom properties from Tiled into Godot. I'm using the tileset attached and importing it into Godot with the custom properties and tile metadata import options ticked. When I add a `TileMap` node and set the `tile_set` property to `tilesetsheet.tsx`, I can access the `tile_meta` dictionary from a script containing the following:
```
extends Node2D

func _ready():
	print($TileMap.tile_set.get_meta("tile_meta"))
```
Attempting to do `print($TileMap.tile_set.get_meta("tile_meta")[0])` gives me `Invalid get index '0' (on base: 'Dictionary').`.

[tilesetsheet.zip](https://github.com/vnen/godot-tiled-importer/files/1683836/tilesetsheet.zip)

**Comment by vnen** [comment]
Now it should work correctly. Note that this fix is not available in the asset lib yet, so you need to download from GitHub.

**Comment by salvob41** [comment]
good fix! We were going crazy about this issue.
