### ISSUE TITLE
Cursor Offset When Placing Tiles in Godot

### ISSUE THREAD

**Issue by atomicbeef** [vnen/godot-tiled-importer#67]
With Godot 3.0-stable and commit e8d89db78e763da0a4fd92a8d1ffef600067229e of this plugin, the tile to be placed is located one tile above where the cursor is. This image illustrates the issue:
![image](https://user-images.githubusercontent.com/10298038/35786962-e08d00a0-09f8-11e8-9b5d-95f1913ccef0.png)
This bug occurs with the following Tiled tileset:
[tilesetsheet.zip](https://github.com/vnen/godot-tiled-importer/files/1693719/tilesetsheet.zip)

**Comment by vnen** [comment]
This offset is needed because in Tiled the origin is bottom-left while in Godot it's top-left. But maybe it could be discarded when importing only the TileSet.
