### ISSUE TITLE
Imported tile indices are off

### ISSUE THREAD

**Issue by SolarLune** [vnen/godot-tiled-importer#68]
Hello. It seems like the tile indices for some tiles are off, making them appear incorrect on the map.  Not sure if I'm just doing something wrong or not.

Here's a simple test tilemap and tileset. 

https://www.dropbox.com/s/vpjt1cqasy7nxer/godotTiledTest.zip?dl=0

Here's also a screenshot. Right's Tiled (how it should appear), and left's Godot (how it does appear).

![screenie](https://user-images.githubusercontent.com/4733521/35900933-44e08590-0b89-11e8-8ac7-1e6f312c7ed1.png)

EDIT: Ah, I forgot to include the png file, but that's okay, I think I figured it out. The plugin assumes the tile sheet source size is a multiple of the tile size when importing. So, if you have 10x10 tiles, you have to have a tilesheet that is sized to a multiple of 10x10, and not a common power of two (i.e. I can't use a 256x256 sized tilesheet).

**Comment by vnen** [comment]
Is this with the Asset Lib version? If so, can you download from GitHub and test it? I think I fixed an issue like this.

**Comment by vnen** [comment]
I assume this is already fixed (just updated the plugin in the AssetLib).
