### ISSUE TITLE
Concave collision not working?

### ISSUE THREAD

**Issue by ZTarget** [vnen/godot-tiled-importer#69]
Hello, the concave collision is not working on import of a tileset (godot 3.0) all are showing up convex.
Is there a way to change the shape manually? like in the .tsx is there a way to change the collision type in notepad? Or is there a way to change the shapetype in godot without losing your shape? 
Thanks
ZTarget

**Comment by vnen** [comment]
Is it not working as is? In my tests the concave shapes did not work at all while convex shapes worked fine (even if the shape itself was concave). In any case, you can make a post-import script that changes the if really needed.

If the collisions aren't working, then I ask for a sample map or tileset so I can test it.

**Comment by ZTarget** [comment]
Here is my test project, hope this helps.
http://www.ektophase.com/otherstuff/ConcaveTest.zip

Thanks

**Comment by vnen** [comment]
Sorry for the delay, should be fixed now in master (will update in AssetLib soon).
