### ISSUE TITLE
Support for hexagonal maps

### ISSUE THREAD

**Issue by vnen** [vnen/godot-tiled-importer#7]

**Comment by FabienDeshayes** [comment]
That would be a feature I'd love to see. Can we know a bit more about what's needed? I suppose we can contribute too.

**Comment by vnen** [comment]
Godot has a demo with Hexagonal maps for reference. Essentially this plugins needs to check for the map format and apply the TileMap settings to work in that way (probably adjusting the Half Offset and Cell Size).

The code should be added around here: https://github.com/vnen/godot-tiled-importer/blob/36669f413ca2d82c14a56a92c9eb3a6292e02715/addons/vnen.tiled_importer/tiled_map_reader.gd#L56-L70

**Comment by vnen** [comment]
The reason I haven't added this yet is because it requires a few calculations to convert the numbers from Tiled to something that looks the same in Godot. I don't have hexagonal maps to test nor the time to figure out the math, so anyone willing is welcome to either implement this or give me a hand with calculations.
