### ISSUE TITLE
problems in large maps. you see lines.

### ISSUE THREAD

**Issue by marianokpo** [vnen/godot-tiled-importer#70]
**Plugin version**
I am using Godot 3.0 stable
Downloaded from the Asset Library

**Issue description**
problems in large maps. you see lines. maps of size 100 * 100 tiles.

**Steps to reproduce**
when loading large maps you see lines that should not be.

**Sample map or tileset**
![imagen](https://user-images.githubusercontent.com/22471380/36096949-60ada288-0fd7-11e8-82e3-0c29890c4828.png)

![imagen](https://user-images.githubusercontent.com/22471380/36096970-80ba1a02-0fd7-11e8-9823-b7b9a264a485.png)

![imagen](https://user-images.githubusercontent.com/22471380/36097137-5c32fb58-0fd8-11e8-9693-202a4649fa09.png)

https://mega.nz/#!PIcx3JhT!njhsSth9eSGq8NCxk1BmHk-u4eLKbB_Qg-J3RRujI38

**Comment by vnen** [comment]
Have you tried enabling "Use Pixel Snap" in the project settings?

**Comment by marianokpo** [comment]
![imagen](https://user-images.githubusercontent.com/22471380/36098464-cb1ffe8a-0fdd-11e8-80b5-4a9c019c022f.png)

the pixel snap is enabled.
"UV Clip" is also enabled by default

(Sorry if you do not understand very well, my English level is not very good.)

**Comment by vnen** [comment]
Reimport the image without filters (using Godot import dock after selecting the image in the FileSystem dock)

Here's what I get with filter:
![godot_2018-02-12_11-26-26](https://user-images.githubusercontent.com/5599796/36098846-aa4e0724-0fe7-11e8-8527-021ffd7f614a.png)
And here's without it:
![godot_2018-02-12_11-26-20](https://user-images.githubusercontent.com/5599796/36098853-b0b4a5f0-0fe7-11e8-9656-8b09b1ac9738.png)

Closing because it's not an issue with the plugin, but feel free to ask if still have any doubt.

**Comment by marianokpo** [comment]
most of the lines went.

they only remain when I zoom with the camara2d of 50%.

![imagen](https://user-images.githubusercontent.com/22471380/36099471-9036cd0e-0fe1-11e8-9c13-4f344aca2054.png)

![imagen](https://user-images.githubusercontent.com/22471380/36099499-ab9814e0-0fe1-11e8-8ddd-a745ec4562f3.png)


From already thank you very much.

**Comment by vnen** [comment]
Are you sure you disabled the filter? Without filter I see no lines at all even when zooming a camera.

**Comment by marianokpo** [comment]
![imagen](https://user-images.githubusercontent.com/22471380/36101107-21ea2476-0fe7-11e8-947d-f14813220323.png)

![imagen](https://user-images.githubusercontent.com/22471380/36101138-36460156-0fe7-11e8-968c-210dccd708c8.png)


https://mega.nz/#!XM10mbiL!1EjthWbfL7gDFNOohYjGrCXHQSoph8p1tFRrtnYs90o


I really do not know if it's something I'm doing wrong. or I did not understand correctly how to do.

the problem in my project you got. I attach the link to my project.

from now, thank you for you help.

**Comment by vnen** [comment]
If you changed that in the TMX (like you do in the picture) you have to set "Embed Internal Images". If not embedded, you need to select the image inside Godot and change the import settings of the image to remove the filter.

**Comment by marianokpo** [comment]
now it works correctly. Thank you so much for your help. :D 💯
