### ISSUE TITLE
Navigation import...

### ISSUE THREAD

**Issue by ay200** [vnen/godot-tiled-importer#72]
**Plugin version**
Tiled Map Importer 2.0, Godot 3.0
Downloaded from Asset Library

**Issue description**
Can't figure out how to import navigation meshes. The README says that types can be assigned as "navigation", but then says that objects in the object layer can't be imported as navigation. However, objects in the object layer are the only way I can see to include polygons in a Tiled map.

I attempted and confirmed that objects in the object layer can't be navigation. Nothing else (tiles, images, etc.) has a type field. How are people importing navigation with their Tiled maps?

**Comment by vnen** [comment]
> However, objects in the object layer are the only way I can see to include polygons in a Tiled map.

You can add objects to individual tiles and set their type, so navigation information is included in the TileSet.

The problem is that AFAIK Godot does not merge multiple navigation polygons. If it's added to the scene it might not work as intended. Maybe I could add this function if people are aware of Godot's limitations, but I'm still not sure how it would work.

**Comment by zombieCraig** [comment]
@ay200 I'm having similar issues.  The navigation polygons are being correctly set and I've verified them my modifying the importer build_tileset_for_scene to print get_tile_navigation_polygon and it's correct.  However the same method of going through all the tileset IDs in godot returns null for every tile.  I have yet to figure out where the disconnect is.

To reproduce.  (in Tiled tileset) Create a collision rect/polygon on a tile and type "navigation" into the type field.  This will create the navpoly's via the importer but in Godot create a simple function like:

```
	var ids = tilemap.tile_set.get_tiles_ids()
	for id in ids:
		var navpoly = tilemap.tile_set.tile_get_navigation_polygon(id)
		if navpoly:
			print("Tile ", id, " has navpoly ", navpoly)
```
all requests will return null (at least in my case)

**Comment by vnen** [comment]
@zombieCraig that's quite odd... I'll have to test it. You can open a new issue about this if you want.

**Comment by raspu** [comment]
I am also seeing the same issues, no tile includes a navigation polygon.

**Comment by zombieCraig** [comment]
@vnen I believe the issue arises when the Tileset has been re-imported but the tilemap was not.  It still doesn't show up via Debug->View Navigation but the polygons are there now and Navigation2D seems to work.
