### ISSUE TITLE
Invalid call. Nonexistent function 'new' in base 'GDScript'.

### ISSUE THREAD

**Issue by SirRamEsq** [vnen/godot-tiled-importer#73]
**I've already solved this issue**, I'm posting it here in case anyone else may run into it. 

When trying to import a tile map I received the following error:
 res://addons/vnen.tiled_importer/tiled_import_plugin.gd:108 - Invalid call. Nonexistent function 'new' in base 'GDScript'

This was strange because I had imported tilemaps before and the custom import script ran without issue and the postImport script looked fine in the editor.

As it turns out, earlier I had moved some constants into a GDScript file that is autoloaded by GODOT. I then tried to reference this autoloaded script inside the postImport TIled Script, but the since the game isn't running at that point, the constants didn't exist. Even though everything looked good in the editor, the script failed, which caused the error.

What got me is that there was a good deal of time between when I had made this change and when I went to reimport a tilemap.

Hope this can help

**Comment by SirRamEsq** [comment]
Closing out

**Comment by vnen** [comment]
Yeah, this is a general issue with Godot, you can't call autoload scripts from the editor. See godotengine/godot#4236.
