### ISSUE TITLE
Collision data in tile objects

### ISSUE THREAD

**Issue by rosshadden** [vnen/godot-tiled-importer#78]
**Plugin version**

`v2.1`, submoduled from github

**Issue description**

Right now, when you add a tile object, the collision data for that tile does not seem to be used.

**Steps to reproduce**

- Add a collision polygon to a tile in a tileset
- Add a tile object to a map, using the tile from above

**Comment by rosshadden** [comment]
I'm not necessarily saying this is a bug. To be clear, I'm talking about Tile objects, not about normal tiles. The collision works great with normal tiles.

Tile objects are imported as `Sprite`s, and I guess I'm not sure how collisions would be supported, but my first guess would be by adding a `CollisionPolygon2D` or `CollisionShape2D` as a child to the sprite.

**Comment by vnen** [comment]
Oh, I misunderstood. Yeah, if you put tiles in an object layer it only makes a Sprite indeed. If it were to support collisions, it would need a physics body together with the sprite.

**Comment by rosshadden** [comment]
@vnen Is this something I can do in an import script? Do I have access to the collision data for the tile somehow?

As it stands, the best workaround I have come up with so far is to make the object in one layer and put the tile on a tile layer, so the collision is imported. This is really disjointed and makes moving such objects all the more difficult.

I'm open to ideas on a better workaround, especially if it's something I can automate in an import script.

**Comment by rosshadden** [comment]
After spending a bunch of time on this, I don't think it's (currently) possible to do in an import script.

I have access to the TileMaps and TileSets of each one, which in turn gives me access to the Shape of each tile in the TileSet (which is the collision shape).  Perfect!  But all I have access to for the Tile Objcet is the texture atlas stuff (image, region, etc).  I don't have the TileSet tile id, and I can't figure it out because I can't search the TileSet by point or region or anything.

Ideally, I wish there was a way to define a Sprite's texture from a TileSet, which is a feature I was going to request in Godot for a completely different use.  I think it would make a lot of sense to be able to assign a specific tile to a sprite, like by dragging it into the texture field or something.  If that feature existed, we could leverage it here instead of using a texture atlas, and I would be able to do everything I need to.  It would also remove the dependency on the sprite sheet image itself, which would let us embed them in the tile maps and not actually commit them to the repo, but that's a side note.

Based on all of this, do you have any ideas of your own?  Do you think we could make something like this possible in this project, by giving the post_import script access to more variables or something?

Thanks!

**Comment by vnen** [comment]
Made an update. Now if the tile has shapes it'll be imported as a StaticBody2D. If the object type is set to `kinematic`, `area`, or `rigid`, the body type will be respected. Using `sprite` as type falls back to just import the sprite and ignores the shapes.

**Comment by rosshadden** [comment]
What happens now is the tile object gets important as a StaticBody2d as you said, but no sprite and no collision. Those could be added manually, but then it's not benefiting from the data that is already present in Tiled.

What I think would make sense is if it created a sprite, and as a child of the sprite it made a StaticBody2d (or kinematic or area or rigid like you just added support for) as a child, and then a CollisionPolygon2d as a child of that which has the same shape as the collision defined on the actual tile in the tileset. The same collision that, were that tile to be placed in a tile layer, would work as expected.

Does that make sense? I'm not sure if it's possible or practical but I think the update you just made kind of just made it worse, lol. Would it help if I made a minimal project and minimal map with this problem present?

**Comment by vnen** [comment]
Is there any error in the console? It should import the sprite and collision nodes as well.
