### ISSUE TITLE
Reparenting node in post_import script not working

### ISSUE THREAD

**Issue by rosshadden** [vnen/godot-tiled-importer#79]
**Plugin version**

`v2.1`, submoduled from github

**Issue description**

I have a small script that simply tries to move all nodes from object layers to a specific layer.
In fact at first it was even more simple, and moved nodes from one specific layer to another specific layer.

The weird part is, it actually... works.  But it's as if the changes aren't persisted or something.
For example, if I log out the nodes in the new parent after doing this, everything is there as expected, but they don't actually show up in the scene or in the game.

**Steps to reproduce**

1. make a map with an object layer and a normal layer (named `main`)
2. add an object to the object layer (Tile object in my case---not sure if important yet)
3. use the following import script:

```gdscript
extends Node

func reparent(child, parent):
	var oldParent = child.get_parent()
	print(oldParent.name, " => ", parent.name, ": ", child.name)
	oldParent.remove_child(child)
	parent.add_child(child)
	child.set_owner(parent)

func post_import(scene):
	var main = scene.get_node("main")

	for layer in scene.get_children():
		if layer is TileMap: continue

		for child in layer.get_children():
			reparent(child, main)
		layer.free()

	return scene
```

Like I said, as far as this script is concerned, it actually works as expected.  But the changes don't actually persist, other than the `layer.free()` part.  And even without that line, the layer isn't removed but the node that should be reparented is gone, not under either parent.

**Comment by rosshadden** [comment]
Maybe it's worth mentioning that the reason I am trying to do this is so that both objects and tiles added through Tiled (and those added through Godot directly) can be children of the same Tilemap, and thus benefit from the same YSort functionality.  If anyone has a better idea for accomplishing this, please let me know.

**Comment by vnen** [comment]
Make sure you set the owner to be the `scene` (which is the root node). If it's anything else Godot will discard it when saving.

**Comment by rosshadden** [comment]
@vnen That was it, thanks!
