### ISSUE TITLE
Index tiles starts from 1 instead of 0

### ISSUE THREAD

**Issue by salvob41** [vnen/godot-tiled-importer#81]
**Plugin version**
Asset Library plugin for Godot 3.0.2stable. Plugin version: 2.0 from Asset library

**Issue description**
Tiles index start counting from 1 except form 0. 
In Tiled the number of the tiles and their index starts from 0. But on Godot it takes the wrong tile. Is there a reason for this behaviour?

**Comment by vnen** [comment]
It uses Tiled global id (`gid`) which always starts from 1. If you're importing only the TileSet, then the id starts from 0.

**Comment by vnen** [comment]
Closing as this is not really an issue.
