### ISSUE TITLE
JSON resource files shadowing by plugin

### ISSUE THREAD

**Issue by salvob41** [vnen/godot-tiled-importer#85]
I use this plugin a lot and it is very helpful, but I came across this weird behaviour. 

**Plugin version**
Asset Library plugin for Godot 3.0.2stable. Plugin version: 2.0 from Asset library

**Issue description**
My project reads a configuration from a JSON file. it works fine in the editor and inside Godot. But when I export the project (doesn't matter if HTML5, MACOSX or Windows) it doesn't seem to read the JSON properly, it gives the following error: 
```

**ERROR**: Condition ' !f ' is true. returned: String()
**ERROR**:    At: core/bind/core_bind.cpp:1597:get_as_text() - Condition ' !f ' is true. returned: String()
**ERROR**: **SCRIPT ERROR**: Invalid call. Nonexistent function 'keys' in base 'Nil'.
```
And even when I flag the "export all resource files" in the appropriate tab (as explained in this answer: https://godotengine.org/qa/27980/get_as_text-condition-returned-reading-exported-project) it gives me the same error.

Thanks to volzhs in the Godot Forum, we figured it that it was because this plugin took permission from all the json files. 

The workaround is explained in this [comment](https://godotengine.org/qa/27980/get_as_text-condition-returned-reading-exported-project?show=27999#c27999): 

> [...] I found importer="vnen.tiled_importer" in .json.import
> I guess it's not about tiled, but the custom importer handle this as resource.
> so after all, it's renamed and moved .import
> if you need that custom importer for your project,
> try different extension name for your data like piece_def.json_data

But is this behaviour supposed to happen?

Thank you for the great work.

**Steps to reproduce**
If you read or write a JSON file, and then export the project

**Sample map or tileset**

**Comment by vnen** [comment]
This is an issue with Godot, since it looks for resource types based on the file extension. There's a note about that on the Readme file:

> **Note:** If you have other `.json` files in your project, this plugin will try to import them and fail. Consider putting those files in a folder alongside a `.gdignore` file so Godot won't try to import them.

I also have been thinking about adding an option in the project settings to disable import of JSON files.

**Comment by salvob41** [comment]
thank you, but I actually DO want Godot to import them, but since it is something the tiled-importer plugin needs, it fails to read from them. 
The plugin could maybe rename those JSON that it needs. Or maybe it could import those JSON that are in specific folders instead all the JSON

**Comment by vnen** [comment]
Added an option in the Project Settings to disable importing JSON files from this plugin. Then you can use TMX and TSX formats for your Tiled maps and JSON format is free for whatever else you need it.
