### ISSUE TITLE
Tiled Importer: Missing or invalid imagewidth tileset property 1.

### ISSUE THREAD

**Issue by gcivicodev** [vnen/godot-tiled-importer#91]
**Plugin version**

2.1

Downloaded from GitHub

**Issue description**

Tiled Importer: Missing or invalid imagewidth tileset property 1.
ERROR: _reimport_file: Error importing: res://Test-Tileset.tsx
   At: editor/editor_file_system.cpp:1441

**Steps to reproduce**

Place your maps inside your project.
Watch Godot import it automatically.

**Sample map or tileset**

[test-tiles.zip](https://github.com/vnen/godot-tiled-importer/files/2199740/test-tiles.zip)

**Comment by gcivicodev** [comment]
Hi. 

I still have this problem. Any idea of what happen?

**Comment by vnen** [comment]
Sorry for the delay. I think this is the same as #88. I have still to update the asset lib version.

**Comment by gcivicodev** [comment]
Ohhh excuse me for that. Yes is the same thing. By the way. Great work !

**Comment by vnen** [comment]
Closing as duplicate. The asset lib version already includes this fix.
