### ISSUE TITLE
Resource was not pre cached for the resource (all tiles turn black)

### ISSUE THREAD

**Issue by girng** [vnen/godot-tiled-importer#97]
**Plugin version**
2.2
godot: 3.1

**Issue description**
when re-importing a .tmx i get:
```
ERROR: Resource was not pre cached for the resource section, bug?
   At: core\io\resource_format_binary.cpp:1507
```

works fine on 3.0.6 tho, hmm

**Comment by shinaka** [comment]
Out of curiosity, would you happen to be testing this on a copy of your project? I had the same issue with the importer and 3.1, and it turned out to be because the tmx was referencing images in my original project folder, and thus were outside the loaded project's resource root. Fixing that made the problem go away.

**Comment by girng** [comment]
> Out of curiosity, would you happen to be testing this on a copy of your project? I had the same issue with the importer and 3.1, and it turned out to be because the tmx was referencing images in my original project folder, and thus were outside the loaded project's resource root. Fixing that made the problem go away.

yeah, actually i am. how u know lol

i made a backup of 3.0 cuz last time 3.1 saved files weird (tscn) and had to edit stuff to reopen. so i just made a backup just in case. should i delete .import and reimport?

**Comment by vnen** [comment]
Might be a bug in Godot.

**Comment by girng** [comment]
@vnen and @shinaka i tried to replicate this in a fresh new project.  i can't. i'm betting it's a rare edge case with my current project (pretty large?)

i have a feeling there might just be linger file laying around causing this. is it possible to delete entire godot cache and .import or something? i bet that might fix it? 
i'll fiddle around with this today and report back if i find anything, this is really got me puzzle'd

**Comment by girng** [comment]
ok. after some testing, i think  the problem is related to setting your tileset's texture in tiled, to a texture that is OUTSIDE of your local game folder.  that's what I did last time, and it worked fine but ran into this issue later.

so, vnen feel free to close if you want, if it happens again now, i'll remake a issue or post here.

**Comment by vnen** [comment]
Sure, thanks for testing it out. I still think this an issue in how Godot handles resources. If you are copying your project somewhere else, deleting the `.import` folder might avoid this.

**Comment by Atermnus** [comment]
Happened to me today in 4.1.

Cannot replicate, seems to happen at random.
